export const gameData = [
  {
    "id":"SL-BB",
    "matrix":{
       "x":5,
       "y":3
    },
    "linesApiData":[
       [
          1,
          1,
          1,
          1,
          1
       ],
       [
          0,
          0,
          0,
          0,
          0
       ],
       [
          2,
          2,
          2,
          2,
          2
       ],
       [
          0,
          1,
          2,
          1,
          0
       ],
       [
          2,
          1,
          0,
          1,
          2
       ],
       [
          0,
          0,
          1,
          0,
          0
       ],
       [
          2,
          2,
          1,
          2,
          2
       ],
       [
          1,
          2,
          2,
          2,
          1
       ],
       [
          1,
          0,
          0,
          0,
          1
       ],
       [
          2,
          0,
          0,
          0,
          2
       ],
       [
          0,
          2,
          2,
          2,
          0
       ],
       [
          2,
          1,
          2,
          1,
          2
       ],
       [
          0,
          1,
          0,
          1,
          0
       ],
       [
          1,
          1,
          2,
          1,
          1
       ],
       [
          1,
          1,
          0,
          1,
          1
       ],
       [
          1,
          0,
          1,
          0,
          1
       ],
       [
          1,
          2,
          1,
          2,
          1
       ],
       [
          2,
          1,
          1,
          1,
          2
       ],
       [
          0,
          1,
          1,
          1,
          0
       ],
       [
          1,
          0,
          2,
          0,
          1
       ],
       [
          2,
          2,
          0,
          2,
          2
       ],
       [
          0,
          0,
          2,
          0,
          0
       ],
       [
          0,
          2,
          0,
          2,
          0
       ],
       [
          2,
          0,
          2,
          0,
          2
       ],
       [
          1,
          2,
          0,
          2,
          1
       ],
       [
          0,
          1,
          2,
          2,
          2
       ],
       [
          2,
          1,
          0,
          0,
          0
       ],
       [
          0,
          0,
          0,
          1,
          2
       ],
       [
          2,
          2,
          2,
          1,
          0
       ],
       [
          0,
          0,
          1,
          2,
          2
       ]
    ],
    "linesCount":[
       1,
       5,
       15,
       20,
       25,
       30
    ],
    "coinsvalue":[
       1,
       2,
       3,
       4,
       5,
       7,
       10,
       15,
       20,
       30
    ],
    "coinsvalueprob":[
       0.60,
       0.25,
       0.10,
       0.03,
       0.01,
       0.005,
       0.003,
       0.001,
       0.0005,
       0.0005
    ],
    "megaLinkCoinValue":[
       2,
       4,
       5,
       6,
       8,
       10,
       15,
       20,
       30,
       50
    ],
    "megaLinkCoinProb":[
       0.60,
       0.25,
       0.10,
       0.03,
       0.01,
       0.005,
       0.003,
       0.001,
       0.0005,
       0.0005
    ],
    "bets":[
       0.0005,
       0.0025,
       0.005,
       0.0125,
       0.025,
       0.0375,
       0.05,
       0.0625,
       0.1,
       0.15,
       0.25,
       0.5,
       0.75,
       1,
       1.5,
       2
    ],
    "jackpot":{
       "payout":[
          5000,
          500,
          100,
          20
       ],
       "payoutProbs":[
          0.0001,
          0.0009,
          0.09,
          0.9
       ]
    },
    "freeSpin":{
       "isEnabled":true,
       "LPValue":[
          2,
          3,
          4,
          5,
          7
       ],
       "LPValueProbs":[
          0.75,
          0.15,
          0.09,
          0.009,
          0.001
       ]
    },
    "bonus":{
       "type":"spin",
       "isEnabled":false,
       "noOfItem":8,
       "payOut":[
          200,
          100,
          70,
          50,
          30,
          20,
          10,
          5
       ],
       "payOutProb":[
          0.001,
          0.004,
          0.006,
          0.008,
          0.05,
          0.10,
          0.15,
          0.75
       ]
    },
    "gamble":{
       "type":"card",
       "isEnabled":false
    },
    "Symbols":[
       {
          "Name":"0",
          "Id":0,
          "reelInstance":{
             "0":15,
             "1":15,
             "2":15,
             "3":15,
             "4":15
          },
          "useWildSub":true,
          "useHeisenberg":false,
          "multiplier":[
             [
                30,
                0
             ],
             [
                15,
                0
             ],
             [
                5,
                0
             ]
          ]
       },
       {
          "Name":"1",
          "Id":1,
          "reelInstance":{
             "0":15,
             "1":15,
             "2":15,
             "3":15,
             "4":15
          },
          "useWildSub":true,
          "useHeisenberg":false,
          "multiplier":[
             [
                30,
                0
             ],
             [
                15,
                0
             ],
             [
                5,
                0
             ]
          ]
       },
       {
          "Name":"2",
          "Id":2,
          "reelInstance":{
             "0":15,
             "1":15,
             "2":15,
             "3":15,
             "4":15
          },
          "useWildSub":true,
          "useHeisenberg":false,
          "multiplier":[
             [
                30,
                0
             ],
             [
                15,
                0
             ],
             [
                5,
                0
             ]
          ]
       },
       {
          "Name":"3",
          "Id":3,
          "reelInstance":{
             "0":15,
             "1":15,
             "2":15,
             "3":15,
             "4":15
          },
          "useWildSub":true,
          "useHeisenberg":false,
          "multiplier":[
             [
                30,
                0
             ],
             [
                15,
                0
             ],
             [
                5,
                0
             ]
          ]
       },
       {
          "Name":"4",
          "Id":4,
          "reelInstance":{
             "0":10,
             "1":10,
             "2":10,
             "3":10,
             "4":10
          },
          "useWildSub":true,
          "useHeisenberg":false,
          "multiplier":[
             [
                70,
                0
             ],
             [
                30,
                0
             ],
             [
                10,
                0
             ]
          ]
       },
       {
          "Name":"5",
          "Id":5,
          "reelInstance":{
             "0":10,
             "1":10,
             "2":10,
             "3":10,
             "4":10
          },
          "useWildSub":true,
          "useHeisenberg":false,
          "multiplier":[
             [
                70,
                0
             ],
             [
                30,
                0
             ],
             [
                10,
                0
             ]
          ]
       },
       {
          "Name":"6",
          "Id":6,
          "reelInstance":{
             "0":10,
             "1":10,
             "2":10,
             "3":10,
             "4":10
          },
          "useWildSub":true,
          "useHeisenberg":false,
          "multiplier":[
             [
                70,
                0
             ],
             [
                30,
                0
             ],
             [
                10,
                0
             ]
          ]
       },
       {
          "Name":"7",
          "Id":7,
          "reelInstance":{
             "0":10,
             "1":10,
             "2":10,
             "3":10,
             "4":10
          },
          "useWildSub":true,
          "useHeisenberg":false,
          "multiplier":[
             [
                70,
                0
             ],
             [
                30,
                0
             ],
             [
                10,
                0
             ]
          ]
       },
       {
          "Name":"8",
          "Id":8,
          "reelInstance":{
             "0":10,
             "1":10,
             "2":10,
             "3":10,
             "4":10
          },
          "useWildSub":true,
          "useHeisenberg":false,
          "multiplier":[
             [
                70,
                0
             ],
             [
                30,
                0
             ],
             [
                10,
                0
             ]
          ]
       },
       {
          "Name":"9",
          "Id":9,
          "reelInstance":{
             "0":30,
             "1":30,
             "2":30,
             "3":30,
             "4":30
          },
          "useWildSub":true,
          "useHeisenberg":true,
          "multiplier":[
            
          ]
       },
       {
          "Name":"Wild",
          "Id":10,
          "reelInstance":{
             "0":8,
             "1":8,
             "2":8,
             "3":8,
             "4":8
          },
          "description":"Substitutes for all symbols except Jackpot, Free Spin, Bonus, and Scatter.",
          "useWildSub":false,
          "useHeisenberg":false,
          "multiplier":[
             
          ]
       },
       {
          "Name":"Link",
          "Id":11,
          "reelInstance":{
             "0":2,
             "1":2,
             "2":2,
             "3":2,
             "4":2
          },
          "description":"",
          "useWildSub":false,
          "useHeisenberg":false,
          "multiplier":[
             
          ]
       },
       {
          "Name":"MegaLink",
          "Id":12,
          "reelInstance":{
             "0":1,
             "1":1,
             "2":1,
             "3":1,
             "4":1
          },
          "description":"",
          "useWildSub":false,
          "useHeisenberg":false,
          "multiplier":[
             
          ]
       },
       {
          "Name":"CashCollect",
          "Id":13,
          "reelInstance":{
             "0":2,
             "1":0,
             "2":0,
             "3":0,
             "4":1
          },
          "description":"",
          "useWildSub":false,
          "multiplier":[
             
          ]
       },
       {
          "Name":"Coins",
          "Id":14,
          "reelInstance":{
             "0":2,
             "1":2,
             "2":2,
             "3":2,
             "4":2
          },
          "description":"",
          "useWildSub":false,
          "useHeisenberg":true,
          "multiplier":[
             
          ]
       },
       {
          "Name":"PrizeCoin",
          "Id":15,
          "reelInstance":{
             "0":1,
             "1":1,
             "2":1,
             "3":1,
             "4":1
          },
          "description":"Substitutes for all symbols except Jackpot, Free Spin, Bonus, and Scatter.",
          "useWildSub":false,
          "useHeisenberg":false,
          "multiplier":[
             
          ]
       },
       {
          "Name":"LosPollos",
          "Id":16,
          "reelInstance":{
             "0":1,
             "1":1,
             "2":1,
             "3":1,
             "4":1
          },
          "description":"",
          "useWildSub":false,
          "useHeisenberg":false,
          "multiplier":[
             
          ]
       }
    ]
 }
]
