

export const gameData = [
   {
      "id":"SL-SM",
      "isSpecial":true,
      "minMatchCount":8,
      "matrix":{
         "x":4,
         "y":4
      },
      "linesCount":[
         25
      ],
      "bets":[
         0.0004,
         0.002,
         0.004,
         0.01,
         0.02,
         0.03,
         0.04,
         0.05,
         0.08,
         0.12,
         0.2,
         0.4,
         0.6,
         0.8,
         1.2,
         1.6,
         2
      ],
      "gamble":{
         "type":"card",
         "isEnabled":true
      },
      "freeSpin":{
         "isEnabled":true,
         "incrementCount":4
      },
      "Symbols":[
         {
            "Name":"0",
            "Id":0,
            "useWildSub":true,
            "isBonusGameSymbol":false,
            "isSpecialSymbol":false,
            "isFreeSpinMultiplier":true,
            "reelInstance":{
               "0":8,
               "1":8,
               "2":8,
               "3":8
            },
            "multiplier":[
               [150,0],
               [50,0],
               [25,0],
               [15,0],
               [10,0],
               [6,0],
               [4,0],
               [3,0],
               [2,0]
            ]
         },
         {
            "Name":"1",
            "Id":1,
            "useWildSub":true,
            "isBonusGameSymbol":false,
            "isSpecialSymbol":false,
            "isFreeSpinMultiplier":true,
            "reelInstance":{
               "0":8,
               "1":8,
               "2":8,
               "3":8
            },
            "multiplier":[
               [50,0],
               [30,0],
               [18,0],
               [12,0],
               [8,0],
               [5,0],
               [3,0],
               [2,0],
               [1,0]
            ]
         },
         {
            "Name":"2",
            "Id":2,
            "useWildSub":true,
            "isBonusGameSymbol":false,
            "isSpecialSymbol":false,
            "isFreeSpinMultiplier":true,
            "reelInstance":{
               "0":8,
               "1":8,
               "2":8,
               "3":8
            },
            "multiplier":[
               [30,0],
               [20,0],
               [13,0],
               [10,0],
               [7,0],
               [4,0],
               [2.50,0],
               [1.50,0],
               [1,0]
            ]
         },
         {
            "Name":"3",
            "Id":3,
            "useWildSub":true,
            "isBonusGameSymbol":false,
            "isSpecialSymbol":false,
            "isFreeSpinMultiplier":true,
            "reelInstance":{
               "0":8,
               "1":8,
               "2":8,
               "3":8
            },
            "multiplier":[
               [20,0],
               [15,0],
               [10,0],
               [7,0],
               [5,0],
               [3,0],
               [2,0],
               [1,0],
               [0.50,0]]
         },
         {
            "Name":"4",
            "Id":4,
            "useWildSub":true,
            "isBonusGameSymbol":false,
            "isSpecialSymbol":false,
            "isFreeSpinMultiplier":true,
            "reelInstance":{
               "0":8,
               "1":8,
               "2":8,
               "3":8
            },
            "multiplier":[
               [15,0],
               [10,0],
               [7,0],
               [5,0],
               [3.50,0],
               [2.50,0],
               [1.50,0],
               [0.80,0],
               [0.40,0]
            ]
         },
         {
            "Name":"5",
            "Id":5,
            "useWildSub":true,
            "isBonusGameSymbol":false,
            "isSpecialSymbol":false,
            "isFreeSpinMultiplier":false,
            "reelInstance":{
               "0":8,
               "1":8,
               "2":8,
               "3":8
            },
            "multiplier":[
               [10,0],
               [7,0],
               [5,0],
               [3,0],
               [2,0],
               [1.50,0],
               [1,0],
               [0.60,0],
               [0.40,0]
            ]
         },
         {
            "Name":"6",
            "Id":6,
            "useWildSub":true,
            "isBonusGameSymbol":false,
            "isSpecialSymbol":false,
            "isFreeSpinMultiplier":false,
            "reelInstance":{
               "0":8,
               "1":8,
               "2":8,
               "3":8
            },
            "multiplier":[
               [8,0],
               [5,0],
               [3,0],
               [2,0],
               [1.50,0],
               [1,0],
               [0.60,0],
               [0.40,0],
               [0.20,0]
            ]
         },
         {
            "Name":"7",
            "Id":7,
            "useWildSub":true,
            "isBonusGameSymbol":false,
            "isSpecialSymbol":false,
            "isFreeSpinMultiplier":false,
            "reelInstance":{
               "0":8,
               "1":8,
               "2":8,
               "3":8
            },
            "multiplier":[
               [6,0],
               [3,0],
               [2,0],
               [1.50,0],
               [1,0],
               [0.60,0],
               [0.40,0],
               [0.30,0],
               [0.20,0]
            ]
         },
         {
            "Name":"Wild",
            "Id":8,
            "useWildSub":false,
            "isBonusGameSymbol":false,
            "isSpecialSymbol":false,
            "isFreeSpinMultiplier":false,
            "reelInstance":{
               "0":5,
               "1":5,
               "2":5,
               "3":5
            },
            "multiplier":[]
   
         },
         {
            "Name":"Bonus",
            "Id":9,
            "useWildSub":false,
            "isBonusGameSymbol":true,
            "isSpecialSymbol":true,
            "isFreeSpinMultiplier":false,
            "reelInstance":{
               "0":5,
               "1":5,
               "2":5,
               "3":5
            },
            "multiplier":[]
   
         },
         {
            "Name":"StickyBonus",
            "Id":10,
            "useWildSub":false,
            "isBonusGameSymbol":true,
            "isSpecialSymbol":true,
            "isFreeSpinMultiplier":false,
            "reelInstance":{
               "0":5,
               "1":5,
               "2":5,
               "3":5
            },
            "multiplier":[]
   
         },
         {
            "Name":"Mystery",
            "Id":11,
            "useWildSub":false,
            "isBonusGameSymbol":true,
            "isSpecialSymbol":false,
            "isFreeSpinMultiplier":false,
            "reelInstance":{
               "0":5,
               "1":5,
               "2":5,
               "3":5
            },
            "multiplier":[
            ]
         },
         {
            "Name":"MoonMystery",
            "Id":12,
            "useWildSub":false,
            "isBonusGameSymbol":true,
            "isSpecialSymbol":false,
            "isFreeSpinMultiplier":false,
            "reelInstance":{
               "0":5,
               "1":5,
               "2":5,
               "3":5
            },
            "multiplier":[
            ]
         },
         {
            "Name":"mini",
            "Id":13,
            "useWildSub":false,
            "isBonusGameSymbol":true,
            "isSpecialSymbol":false,
            "isFreeSpinMultiplier":false,
            "reelInstance":{
               "0":5,
               "1":5,
               "2":5,
               "3":5
            },
            "multiplier":[
            ]
         },
         {
            "Name":"minor",
            "Id":14,
            "useWildSub":false,
            "isBonusGameSymbol":true,
            "isSpecialSymbol":false,
            "isFreeSpinMultiplier":false,
            "reelInstance":{
               "0":5,
               "1":5,
               "2":5,
               "3":5
            },
            "multiplier":[
            ]
         },
         {
            "Name":"major",
            "Id":15,
            "useWildSub":false,
            "isBonusGameSymbol":true,
            "isSpecialSymbol":false,
            "isFreeSpinMultiplier":false,
            "reelInstance":{
               "0":5,
               "1":5,
               "2":5,
               "3":5
            },
            "multiplier":[
            ]
         },
         {
            "Name":"MOON",
            "Id":16,
            "useWildSub":false,
            "isBonusGameSymbol":true,
            "isSpecialSymbol":false,
            "isFreeSpinMultiplier":false,
            "reelInstance":{
               "0":5,
               "1":5,
               "2":5,
               "3":5
            },
            "multiplier":[
            ]
         }
      ]
   }

]